import { AppSidebar } from "@/components/my/sidebar/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ComponentsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar collapsible="none" className="pl-3 pr-3" />
      <section className="p-5">{children}</section>
    </SidebarProvider>
  );
}
